version: '3'
services:

  masscan:
    environment:
      MASSCAN_ARGS: -p80,8080,443,4443,21,22,23,5432,3389,123,69,110,995,143,993,25,587,3306 --banners --rate 10000 10.10.1.0/24
      GTW_ADDR: 10.10.1.1
    networks:
      - basic_nginx
    depends_on:
      - nginx

  nginx:
    networks:
      - basic_nginx
    
networks:
  basic_nginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
