version: '3'
services:

  masscan:
    environment:
      MASSCAN_ARGS: -p80 10.10.1.0/24
    networks:
      - basic_nginx
    depends_on:
      - nginx

  nginx:
    networks:
      - basic_nginx
    
networks:
  basic_nginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
