version: '3'
services:

  masscan:
    environment:
      MASSCAN_ARGS: -p80,8080,443,4443,21,22,23,5432,3389,123,69,110,995,143,993,25,587,3306 --banners --rate 10000 10.11.2.1/24
      GTW_ADDR: 10.11.2.1
    networks:
      - big_net
    depends_on:
      - nginx
      - ftp_1
      - ftp_2
      - ftp_3
      - telnet_1
      - telnet_2
      - telnet_3
      
  nginx:
    networks:
      - big_net

  ftp_1:
    image: delfer/alpine-ftp-server
    container_name: ftp_1
    restart: unless-stopped
    environment:
      USERS: "pepe|UltraSecurePassword34902356"
    ports:
      - "2100:21"
    networks:
      - big_net
 
  ftp_2:
    image: delfer/alpine-ftp-server
    container_name: ftp_2
    restart: unless-stopped
    environment:
      USERS: "pepe|UltraSecurePassword34902356"
    ports:
      - "2101:21"
    networks:
      - big_net
 
  ftp_3:
    image: delfer/alpine-ftp-server
    container_name: ftp_3
    restart: unless-stopped
    environment:
      USERS: "pepe|UltraSecurePassword34902356"
    ports:
      - "2102:21"
    networks:
      - big_net
 

  telnet_1:
    image: secobau/telnetd:alpine
    container_name: telnet_1
    restart: unless-stopped
    ports:
      - "2300:23"
    networks:
      - big_net

  telnet_2:
    image: secobau/telnetd:alpine
    container_name: telnet_2
    restart: unless-stopped
    ports:
      - "2301:23"
    networks:
      - big_net
  
  telnet_3:
    image: secobau/telnetd:alpine
    container_name: telnet_3
    restart: unless-stopped
    ports:
      - "2302:23"
    networks:
      - big_net
  

networks:
  big_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.2.0/24
          gateway: 10.11.2.1
