version: '3'
services:

  masscan:
    environment:
      MASSCAN_ARGS: -p80,8080,443,4443,21,22,23,5432,3389,123,69,110,995,143,993,25,587,3306 --banners --rate 10000 10.11.1.1/24
    networks:
      - small_net
    depends_on:
      - nginx
      - ftp
      - telnet

  nginx:
    networks:
      - small_net

  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp
    restart: unless-stopped
    environment:
      USERS: "pepe|UltraSecurePassword34902356"
    ports:
      - "21:21"
    networks:
      - small_net
 
  telnet:
    image: secobau/telnetd:alpine
    container_name: telnet
    restart: unless-stopped
    ports:
      - "23:23"
    networks:
      - small_net

networks:
  small_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.1.0/24
          gateway: 10.11.1.1
